In [1]:
print('yo')

yo


In [12]:
x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [14]:
y=list(x)

In [15]:
y

[1, 2, 3, 4, 5]

In [16]:
x[2]=100

In [17]:
y

[1, 2, 3, 4, 5]

In [21]:
try:
    3+'candy'
except:
    print('thats alright, go ahead')

thats alright, go ahead


In [31]:
def myfunction(x,y, z=10):
    print('x is {0}, y is {1}, z is {2}'.format(x,y,z))

In [33]:
myfunction(4,3)

x is 4, y is 3, z is 10


In [12]:
def f2(x,y,*args,**kwargs):
    print('x is {},y is {}'.format(x,y))
    print(args)
    print(kwargs)

In [13]:
f2(3,4,3,5,6,1, day='Thursday')

x is 3,y is 4
(3, 5, 6, 1)
{'day': 'Thursday'}


In [2]:
x=[1,2,3,4,5]
y=x

In [3]:
zip(x,y)

In [4]:
for a,b in zip (x,y):
    print(a,b)

1 1
2 2
3 3
4 4
5 5


In [8]:
animal=['dog', 'cat', 'bat']

In [9]:
i=0
for i in animal:
    print(i)

dog
cat
bat


In [17]:
import numpy as np

In [22]:
a=np.nonzero((3,5))

In [25]:
b=np.linspace(0,2.5,100, False)

In [26]:
a

(array([0, 1]),)

In [29]:
c=np.array(range(10))

In [30]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
d=np.array([2,4,6])

In [32]:
d

array([2, 4, 6])

In [33]:
print(d)

[2 4 6]


In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import timeit
points=[100,1000,10000,100000]
sqrt=math.sqrt
inside=0
for npoints in points:
    for i in range(0,npoints):
        circ=np.random.rand(1,2)
        x=circ[:,0]
        y=circ[:,1]
        #print('x is', x)
        r=sqrt(x**2+y**2)
        #print('circ is', circ)
        #print('this was',i)
        if r<=1:
            inside+=1
            #print('good radius is ',r)
    pi=4*inside/npoints
    print('pi is', pi)
    time=timeit.timeit(number=npoints)
    print('calculates in',time, ' seconds')

pi is 3.16
calculates in 2.284068614244461e-06  seconds
pi is 3.5
calculates in 2.03580129891634e-05  seconds
pi is 3.47
calculates in 0.00016974681057035923  seconds
pi is 3.49296
calculates in 0.0019912919960916042  seconds


In [14]:
import numpy as np
import math
import matplotlib.pyplot as plt
import timeit
points=[100,1000,10000,100000]
a=[0,points[0]-1]
b=[points[0],points[1]-1]
c=[points[1],points[2]-1]
d=[points[2],points[3]-1]
bins=[a,b,c,d]
print(bins)
sqrt=math.sqrt
times=np.empty((4,1))
for i in range(0,4):
    time=timeit.timeit(number=points[i])
    print('calculates in',time, ' seconds')
    times[i]=time
print(times)

[[0, 99], [100, 999], [1000, 9999], [10000, 99999]]
calculates in 2.817949280142784e-06  seconds
calculates in 2.0758016034960747e-05  seconds
calculates in 0.00020076101645827293  seconds
calculates in 0.00249562319368124  seconds
[[  2.81794928e-06]
 [  2.07580160e-05]
 [  2.00761016e-04]
 [  2.49562319e-03]]
