In [5]:
import numpy as np
x=np.arange(12).reshape((4,3))
print(x)
y=x[-2:,:].copy()#-2nd row and everything down, everything in those rows
y*=100
y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 600,  700,  800],
       [ 900, 1000, 1100]])

In [18]:
def myfn(arr):
    #arr=arr.copy()
    arr=arr*2
    #print('hi')
    print(arr)

In [19]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
myfn(x)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [17]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
N=1000
x=-1+2*np.random.rand(N)
y=-1+2*np.random.rand(N)
inside=(x**2+y**2<1).sum()
frac=inside*1./N

In [31]:
def myfunction(x,y, z=10):
    print('x is {0}, y is {1}, z is {2}'.format(x,y,z))

In [33]:
myfunction(4,3)

x is 4, y is 3, z is 10


In [24]:
import numpy as np
from __future__ import division

def estimatePi(N):
    inside=(x**2+y**2<1).sum()
    frac=inside*1./N
    pi=frac*4
    return pi

In [28]:
Ns=[10,100,1000,10000,100000]
pis=[estimatePi(N) for N in Ns]

In [29]:
for N in Ns:
    print(estimatePi(N))

320.0
32.0
3.2
0.32
0.032


In [3]:
zip(x,y)

In [4]:
for a,b in zip (x,y):
    print(a,b)

1 1
2 2
3 3
4 4
5 5


In [8]:
animal=['dog', 'cat', 'bat']

In [9]:
i=0
for i in animal:
    print(i)

dog
cat
bat


In [17]:
import numpy as np

In [22]:
a=np.nonzero((3,5))

In [25]:
b=np.linspace(0,2.5,100, False)

In [26]:
a

(array([0, 1]),)

In [29]:
c=np.array(range(10))

In [30]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
d=np.array([2,4,6])

In [32]:
d

array([2, 4, 6])

In [33]:
print(d)

[2 4 6]


In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import timeit
points=[100,1000,10000,100000]
sqrt=math.sqrt
inside=0
for npoints in points:
    for i in range(0,npoints):
        circ=np.random.rand(1,2)
        x=circ[:,0]
        y=circ[:,1]
        #print('x is', x)
        r=sqrt(x**2+y**2)
        #print('circ is', circ)
        #print('this was',i)
        if r<=1:
            inside+=1
            #print('good radius is ',r)
    pi=4*inside/npoints
    print('pi is', pi)
    time=timeit.timeit(number=npoints)
    print('calculates in',time, ' seconds')

pi is 3.16
calculates in 2.284068614244461e-06  seconds
pi is 3.5
calculates in 2.03580129891634e-05  seconds
pi is 3.47
calculates in 0.00016974681057035923  seconds
pi is 3.49296
calculates in 0.0019912919960916042  seconds


In [36]:
import numpy as np
import math
import matplotlib.pyplot as plt
import timeit
points=[10, 100,1000,10000,100000]
sqrt=math.sqrt
inside=0
repeat=1
Nruns=1000
if repeat:
    points=[10, 100,1000,10000,100000]
    length=len(points)
    pis=[]
   
    pisst=[]
    for i in range(0,length):
        pisj=[]
        for j in range(0,Nruns):
            N=points[i]
            x=-1+2*np.random.rand(N)
            y=-1+2*np.random.rand(N)
            inside=(x**2+y**2<1).sum()
            pi=4*inside/N
            #print('pi is', pi)
            pisj.append(pi)
        pisj=np.array(pisj)
        #print(pism)
        print(pisj.mean(), pisj.std())
        #pis.append(pi)
        #pisst.append(pisj)
    #print(pisst)
    #pisst=np.array(pisst)

3.1432 0.522430626974
3.14272 0.165308806783
3.143892 0.0513541851849
3.1417652 0.016437257343
3.14176988 0.00507001285852


In [45]:
import numpy as np
data = np.genfromtxt('/Users/amandanewmark/repositories/usrp-sciprog/projects/hubble/table1.txt', dtype=None, names=True)

In [47]:
data['R']

array([ 0.032,  0.034,  0.214,  0.263,  0.275,  0.275,  0.45 ,  0.5  ,
        0.5  ,  0.63 ,  0.8  ,  0.9  ,  0.9  ,  0.9  ,  0.9  ,  1.   ,
        1.1  ,  1.1  ,  1.4  ,  1.7  ,  2.   ,  2.   ,  2.   ,  2.   ])